// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZbVavGE5tGkbswGgi-3BYW8SvZl-GLOM',
    appId: '1:462284266491:web:96b0e9b94a8ebbf5e9095e',
    messagingSenderId: '462284266491',
    projectId: 'hubify-29a72',
    authDomain: 'hubify-29a72.firebaseapp.com',
    storageBucket: 'hubify-29a72.firebasestorage.app',
    measurementId: 'G-FGDCRHSP8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzLFMNuX_71ydr28q_YqjJsYgYWs_9kNo',
    appId: '1:462284266491:android:6ffefff7d128847ce9095e',
    messagingSenderId: '462284266491',
    projectId: 'hubify-29a72',
    storageBucket: 'hubify-29a72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8kr-GWcumQT-5pRbboqLWns135VHbX0I',
    appId: '1:462284266491:ios:02404477475d3ecbe9095e',
    messagingSenderId: '462284266491',
    projectId: 'hubify-29a72',
    storageBucket: 'hubify-29a72.firebasestorage.app',
    iosClientId: '462284266491-bur9s8cj7iq5t553ijkkeohhadnufvdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.hubify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8kr-GWcumQT-5pRbboqLWns135VHbX0I',
    appId: '1:462284266491:ios:02404477475d3ecbe9095e',
    messagingSenderId: '462284266491',
    projectId: 'hubify-29a72',
    storageBucket: 'hubify-29a72.firebasestorage.app',
    iosClientId: '462284266491-bur9s8cj7iq5t553ijkkeohhadnufvdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.hubify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZbVavGE5tGkbswGgi-3BYW8SvZl-GLOM',
    appId: '1:462284266491:web:62c3e7db447115a6e9095e',
    messagingSenderId: '462284266491',
    projectId: 'hubify-29a72',
    authDomain: 'hubify-29a72.firebaseapp.com',
    storageBucket: 'hubify-29a72.firebasestorage.app',
    measurementId: 'G-D7EC53QC91',
  );
}
